### ISSUE TITLE
'ClovaX' object has no attribute 'continue_conversation'

### ISSUE THREAD

**Issue by teddylee777** [mirusu400/CLOVA-X#3]
안녕하세요?

좋은 래핑 라이브러리 만들어 주셔서 감사합니다.
ClovaX 객체의 continue_conversation() 실행시 no attribute 에러가 발생하고
코드를 살펴보니 메서드가 누락된 것으로 보입니다.

감사합니다.

**Comment by mirusu400** [comment]
확인 감사합니다

분명히 구현한 기억이 있는데 커밋 이력 보니까 추가가 안되어있네요.. 😅

확인후에 수정하도록 하겠습니다.

**Comment by mirusu400** [comment]
확인해보니 `continue_conversation` 메서드 명으로 구현한것이 아닌 `conversaion` 메서드로 구현되어있네요. 해당 메서드를 사용해주시면 됩니다.

ex.
```python
from clovax import ClovaX

c = ClovaX()
c.get_cookie("[Your netscape cookie file]")
log = c.start("Hello world!")
print(log["text"])
# At this time, you can continue the conversation using existed session (conversation ID)
log = c.conversation("Who are you?")
print(log["text"])
```
